# Configuration for Label Actions - https://github.com/dessant/label-actions

# Base PR and issues lifecycle
needs-triage:
  unlabel:
  - 'needs-feedback'
  - 'acknowledged'

needs-feedback:
  unlabel:
  - 'needs-triage'
  - 'acknowledged'

acknowledged:
  unlabel:
  - 'needs-feedback'
  - 'needs-triage'

# The `wontfix` label is removed from issues
wontfix:
  unlabel:
  - 'needs-feedback'
  - 'needs-triage'
  - 'acknowledged'
  close: true
